# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-21 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lev_num', models.IntegerField(default=1)),
                ('is_emer', models.BooleanField(default=False)),
                ('emer_col', models.CharField(default=None, max_length=4, verbose_name=['red', 'yellow', 'green', 'blue'])),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rank', models.IntegerField(blank=True)),
                ('lev_num', models.IntegerField(default=1)),
                ('num_diamonds', models.IntegerField(default=100)),
                ('is_emer_red', models.BooleanField(default=False)),
                ('is_emer_blue', models.BooleanField(default=False)),
                ('is_emer_green', models.BooleanField(default=False)),
                ('is_emer_yellow', models.BooleanField(default=False)),
                ('num_emers', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob_num', models.IntegerField(blank=True, default=None)),
                ('answer', models.CharField(max_length=1000)),
                ('prob_num_diam', models.IntegerField(default=50)),
                ('prob_hint', models.CharField(max_length=1000)),
                ('prob_help', models.CharField(max_length=1000)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='L_F_app.Level')),
            ],
        ),
    ]
