# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-21 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L_F_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='is_emer',
            new_name='is_emer_blue',
        ),
        migrations.RemoveField(
            model_name='level',
            name='emer_col',
        ),
        migrations.AddField(
            model_name='level',
            name='is_emer_green',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='level',
            name='is_emer_red',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='level',
            name='is_emer_yellow',
            field=models.BooleanField(default=False),
        ),
    ]
