# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-22 06:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('L_F_app', '0002_auto_20171221_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
