# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-22 11:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('L_F_app', '0004_auto_20171222_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
