# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-25 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAUapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custuser',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
